### PR TITLE
Updated for better developer experience

### PR DESCRIPTION
**Pull request by silentworks**
I have created a better developer experience with the new API design. 

- Abstracted away things that the developer shouldn't be worrying about like namespace, wsdl, version and so forth.
- Added in unit tests to show.
- Added in better object creation classes like OrderItem and OrderItems
- PSR4 support added
- Composer ready

### CODE REVIEW

**Comment by kdjomeda** [comment]
Hello Silentworks, looks good to me. Will review and merge in the course of the week. Thanks a million

**Comment by silentworks** [comment]
I have done a quick setup example code showing how this would work in an simple application here https://github.com/silentworks/slydepay-rest-api-wrapper-test

**Comment by kdjomeda** [comment]
Hello Silentworks merged this to a different branch [1.1.0-stable](https://github.com/DreamOval/slydepay-php-connector/tree/1.1.0-stable)

**Comment by silentworks** [comment]
So by doing this you have erased every existence of my contribution to this project. I don't think this is how pull requests work on github, also what would be the reason to move my code to a different branch without first merging it into master.

**Comment by kdjomeda** [comment]
Oh no, take it easy, I planned to merge it back to master. You know there are different philosophies on how master is kept.  Please check the branch all your stuff are there and I have not plan on removing the awesome work you have done. So chill, we are cool , I am not removing your name anywhere. Even my comment said "committing silentworks contribution".

**Comment by kdjomeda** [comment]
Hello Silentworks no issue, I will merge it to master.

**Comment by silentworks** [comment]
Thank you @kdjomeda, if you notice a few methods missing, its because I couldn't find them in your official API documentation.

**Comment by kdjomeda** [comment]
Hello @silentworks pushed changes to master. Will have my team do further test and will release and have it in composer. Thanks for the good work so far

**Comment by silentworks** [comment]
Hi @kdjomeda I would suggest changing the order of the params in the new `Order` object, since `comment` is not a required field, move it to the end.

So instead of:

```php
public function __construct($orderCodeOrId = null,
                                $shippingCost = null,
                                $taxAmount = null,
                                $description = null,
                                $comment = null,
                                OrderItems $orderItems)
```

Have this instead:

```php
public function __construct(
    $orderCodeOrId = null,
    $shippingCost = null,
    $taxAmount = null,
    $description = null,
    OrderItems $orderItems,
    $comment = null
) {
```

I would also suggest following the PSR-2 coding standard as I notice all different type of formatting going on with the changes you have made. You can use the command line code formatting tool to format the code after for PSR-2.

**Comment by silentworks** [comment]
@kdjomeda this bit of code looks like a hack https://github.com/DreamOval/slydepay-php-connector/blob/master/src/Slydepay.php#L65, shouldn't the API endpoint throw an exception instead of you having to check the result in this code than throwing an exception?

**Comment by kdjomeda** [comment]
@silentworks as per documented here on the [api doc](https://s3.amazonaws.com/slydepay-public/docs/SlydepayMerchantApi_V_1.4.pdf) on page 10. If there is an issue with the call to Slydepay, instead of it throwing an exception, it could throw Error: 1 when there is an issue with the credentials or Error: 3 when merchant is not verified etc. So you ought to check if that's a valid token before you attempt on sending back a URL link. I hope you get it

**Pull request merged**
